services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - ".dockerfs/mqtt/mosquitto:/mosquitto"
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto/config/mosquitto.conf"
